[pytest]
# Busca los tests dentro de la carpeta del proyecto
testpaths = demo_sonarqube_project/tests

# Añade demo_sonarqube_project al PYTHONPATH para que 'src' se pueda importar
pythonpath = demo_sonarqube_project

# Opcional: flags útiles
addopts = --maxfail=1 -q --disable-warnings
